; This is required to insert the object file header generated by GASM.
; rmac doesn't support this type of file header, so we just create
; an absolute binary with leading bytes of $00f0,$3000,$0000,$01cc 
.org $0000
.dc.w $00f0,$3000,$0000,$01cc 
.incbin "bin/gpudave.o"
